# Generated by Django 4.0.4 on 2022-05-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='percentage_complete',
            new_name='percentage_completed',
        ),
    ]
