# Generated by Django 3.2.13 on 2022-05-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=3, help_text='Number of questions to be asked in the quiz.'),
        ),
    ]
