# Generated by Django 4.0.4 on 2022-05-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Price in BRL cents', verbose_name='Price in BRL cents')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='buyers.buyer')),
            ],
        ),
    ]
