# Generated by Django 4.0.4 on 2022-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('action', models.CharField(choices=[('NO_FILTER', 'No Filter'), ('COLORIZED', 'Colorized'), ('GRAYSCALE', 'Grayscale'), ('BLURRED', 'Blurred'), ('BINARY', 'Binary'), ('INVERT', 'Invert')], default='NO_FILTER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
