# Generated by Django 4.0.4 on 2022-06-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='_picture',
            field=models.ImageField(blank=True, upload_to='posts/pictures/', verbose_name='Picture'),
        ),
    ]
