# Generated by Django 4.0.4 on 2022-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_picture_post__picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_picture',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='posts/pictures/'),
        ),
    ]
