# Generated by Django 4.0.4 on 2022-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_avatar_profile_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/avatars/default.png', upload_to='avatars/'),
        ),
    ]
